[build]
target = "thumbv7em-none-eabi"

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# replace nRF82840_xxAA with your chip as listed in `probe-rs chip list`
runner = "probe-rs run --chip nRF52840_xxAA"
# runner = "probe-run --chip nRF52840_xxAA --defmt"

[unstable]
#build-std-features = ["panic_immediate_abort"]

# For host builds and STD targets
build-std = ["core", "alloc", "panic_abort"]

# [env]
# DEFMT_LOG = "trace"
