[package]
name = "rs-matter-embassy"
version = "0.1.0"
authors = ["ivmarkov <ivan.markov@gmail.com>"]
edition = "2021"
resolver = "2"
categories = ["embedded", "hardware-support"]
keywords = ["matter", "embedded", "embassy"]
description = "Run rs-matter with embassy"
repository = "https://github.com/ivmarkov/rs-matter-embassy"
license = "MIT OR Apache-2.0"
readme = "README.md"
rust-version = "1.84"

[lib]
harness = false

#[patch.'https://github.com/ivmarkov/rs-matter-stack']
#rs-matter-stack = { path = "../../rs-matter-stack" }
#[patch.'https://github.com/embassy-rs/trouble']
#trouble-host = { version = "0.1", path = "../../trouble/host" }

[patch.crates-io]
#rs-matter = { git = "https://github.com/project-chip/rs-matter" }
rs-matter = { git = "https://github.com/ivmarkov/rs-matter", branch = "pase-breaks-provisioning" }
nrf-sdc = { git = "https://github.com/alexmoon/nrf-sdc.git", rev = "551a95436e999b4290b4a33383aa3d6747b63dd9" }
nrf-mpsl = { git = "https://github.com/alexmoon/nrf-sdc.git", rev = "551a95436e999b4290b4a33383aa3d6747b63dd9" }

[profile.release]
opt-level = "s"

[profile.dev]
debug = true
opt-level = "z"

[features]
default = ["rs-matter-stack"]
esp = ["esp-wifi", "esp-hal"]
rp = ["cyw43", "cyw43-pio", "embassy-rp", "rand_core"]
nrf = ["embassy-nrf", "rand", "nrf-sdc", "nrf-mpsl"]

[dependencies]
log = { version = "0.4", default-features = false }
heapless = "0.8"
embassy-futures = "0.1"
embassy-sync = "0.6"
embassy-time = "0.4"
embassy-net = { version = "0.6", features = ["proto-ipv4", "proto-ipv6", "multicast", "dhcpv4"] }
edge-nal-embassy = "0.5"
embedded-storage-async = "0.4.1"
sequential-storage = "3"
trouble-host = { version = "0.1", git = "https://github.com/embassy-rs/trouble" }
bt-hci = "0.2"
embedded-io = "0.6"
scopeguard = { version = "1", default-features = false }
rs-matter = { version = "0.1", default-features = false, features = ["rustcrypto"] }
rs-matter-stack = { git = "https://github.com/ivmarkov/rs-matter-stack", default-features = false, optional = true, features = ["rustcrypto"] }
static_cell = "2"

# Only necessary when `rs-matter-embassy` is providing extra-sugar for the `esp32*` chips family
esp-wifi = { version = "0.12", optional = true, features = ["wifi", "ble"] }
esp-hal = { version = "0.23", optional = true, features = ["unstable"] }

# Only necessary when `rs-matter-embassy` is providing extra-sugar for the RPi Pico W MCU
cyw43 = { version = "0.3", optional = true, features = ["firmware-logs", "bluetooth"] }
cyw43-pio = { version = "0.3.0", optional = true }
embassy-rp = { version = "0.3.0", optional = true, features = ["unstable-pac", "rp2040"] }
rand_core = { version = "0.6.4", optional = true }

# Only necessary when `rs-matter-embassy` is providing extra-sugar for Nordic silicon
# embassy-nrf = { version = "0.3.1", features = ["nrf52840",  "time-driver-rtc1", "time"], default-features = false }
embassy-nrf = { version = "0.3.1", optional = true, features = ["log", "time-driver-rtc1", "time", "nrf52840"], default-features = false }
rand = { version = "0.8.4", optional = true, default-features = false }
nrf-sdc = {  git = "https://github.com/alexmoon/nrf-sdc.git", rev = "551a95436e999b4290b4a33383aa3d6747b63dd9", version = "0.1.0", optional = true, default-features = false, features = ["nrf52840", "peripheral", "central"] }
nrf-mpsl = { git = "https://github.com/alexmoon/nrf-sdc.git", rev = "551a95436e999b4290b4a33383aa3d6747b63dd9", version = "0.1.0", optional = true, default-features = false, features = ["critical-section-impl"] }
